### ISSUE TITLE
Feature request: generate separate playlist per day

### ISSUE THREAD

**Issue by leccelecce** [dot4qu/Lineup-List#18]
Currently I assume (untested) that for say a four-day festival, if I wanted four separate playlists I could achieve this by ticking one day at a time on the customize screen and going through the generation process four times. That's a reasonable amount of effort, especially if the lineup is changing frequently.

What I'm thinking is a radio button on the customize screen along the lines of "Create single playlist" / "Create playlist per day" at the bottom of the Playlist Options section, defaulting to the current behaviour. For festivals with no separate days data the checkbox wouldn't be shown.

Having had a guess at what would need changing, I think this would be a reasonable amount of change across the pages/api/spotify/redis logic so haven't created a PR. If you approve of the idea I might consider it at some point.

**Comment by dot4qu** [comment]
I'm not too sure this adds enough value to add as a feature. Like you said, manually generating a new playlist for each day works fine. The page remembers your selections too, so it's like ~3 minutes of work to create 3 playlists for each day of the festival.
I hear you that it could get annoying if you're regenerating the playlists multiple times, but in my experience festival lineups don't really change that much leading up to it. Covid has made it a bit shakier, but for the most part I really only see one shuffle of artists a month or two before some festivals. Most of the time it's few enough artists it's probably quicker just to delete / add some songs in spotify itself.
I think I'm going to hold off on this one for now - if multiple people request it I'm happy to reconsider

**Comment by leccelecce** [comment]
You know - I hadn't actually noticed how easy this was - agreed it would overcomplicated things. Thanks for taking the time to provide feedback.

**Comment by dot4qu** [comment]
That's one of the main improvements on the todo list for this project that I've had for a while haha. I think it would be a good option to have even though it adds a bit of complication of the edge case of overwriting existing playlists that we maybe won't have permission for.
