### ISSUE TITLE
Feature request: last updated date on lineups

### ISSUE THREAD

**Issue by leccelecce** [dot4qu/Lineup-List#19]
Self explanatory really. With changing line-ups, how do I know if there are potentially bands that are missing or have dropped out. Data could potentially be months out of date if it hasn't been checked in a while. There are two use cases here; curious users having some visibility, and contributors of line up data such as myself having a straightforward way to check if something hasn't been updated in a while (beyond checking this repo).

For end-user visibility I think it's probably just something like the below:

![image](https://user-images.githubusercontent.com/24962424/176044432-a86cb29d-beee-45c6-b279-77a423b0b67a.png)

For contributors, perhaps a readonly API endpoint that returns array of festival name, year, last modified datestamp.

Happy to send a PR. In terms of storage I have a few thoughts on different ways this could be done - datestamp in the lineup .txt filename, datestamp as the first row of the filename, some other field in redis- but I'm conscious you may have some scraper scripts that generate the existing range of files.

Historic population for those festivals remaining in 2022 could probably be done by git commit timestamp

**Comment by dot4qu** [comment]
Seems like a reasonable change, but I'm not sure the majority of users will get that much use out of it for me to implement.

If you'd like to add it, go ahead! I think the way id do it is just add a new redis key for each festival for the date updated, then when pulling festival data out of redis when loading each lineup page it's a simple query. 

On mobile right now so I need to double check what the keys are, but I think festival metadata is saved as `festival:name_year:metadataname`. So this would be a new key called `festival:name_year:last_updated_date`. 

(Ideally I'd switch the metadata to one blob cache entry so days/last updated/etc are all stored and retrieved under one key like artist data, but that would require touching even more logic in the codebase for proper retrieval which I'd rather avoid)

The existing festivals will need to be backfilled in redis so they all have last updated dates. Simplest way is to set them all to now, better would be to use the last edit date of the festival text file (not sure if git preserves these attributes or that would only work on my filesystem). 

Another option would be to not backfill and have whatever handlebars helper displays this date just not display any text if there's no last updated date given

**Comment by leccelecce** [comment]
No worries I was proposing to send a PR - just wanted to check approval on direction of travel before starting on it. Redis key makes sense.

**Comment by dot4qu** [comment]
https://github.com/dot4qu/Lineup-List/blob/master/src/warm-cache-for-festival.ts#L49-L51

This would be the line to duplicate but for `last_updated_date`
