### ISSUE TITLE
Latest tracks for artist never refreshed after initial cache input

### ISSUE THREAD

**Issue by leccelecce** [dot4qu/Lineup-List#42]
Another proposed PR I would like to run by you before working on.

As far as I can tell from casual observation and a look in [`redis-helper.ts`](https://github.com/dot4qu/Lineup-List/blob/bc1a418b339951fc603774cd5a953a68221d0b72/src/redis-helper.ts), once the cache warm script is run and identifies tracks (top, newest, or setlist) for an artist, these are persisted to Redis and never expired (unless you're either setting expiries somewhere I've missed, or running a script outside of version control to periodically delete out artist/track keys and then re-running the cache warmer).

This runs the risk that the tracks added to 2022 or 2023 playlists for artists who were at say, Coachella in 2020, (probably playing songs from 2019 and earlier) will get something reasonably out of date. This would particularly impact "newer" artists who only have 1-2 albums and so a lot of their material can be relied on to change.

There are a number of different ways this could be enhanced. I was thinking that as a short-term solution, the warm cache script could be changed to refresh the data for all artists being loaded from a lineup i.e. treat them as new to ensure the latest data is added. This would slow down the cache warm operation, but is a straightforward change.

The longer term solution is probably a scheduled background process to periodically cycle through artists and refresh them. I'm assuming it would be preferable to do this in the background rather than on-demand from the front-end, as larger festivals can have 70+ artists which could slow down the playlist generation process considerably. There are different ways this could be implemented but I'm not proposing that at this stage.

**Comment by dot4qu** [comment]
Haha this was very much a "I'll handle it when it becomes a problem" solution for me when I implemented the logic. I think you're correct in that it's definitely time to start cycling back through old artists and getting new top/new/setlist songs saved.

It's just such a pain to have to wait ~15-20 minutes for a full run of that script when adding a new festival, versus the ~2-4 it takes now that the cache is seeded with a lot of the common festival artists currently.

I feel like it'd almost be better to do it on an artist-by-artist basis. Maybe add a `last_updated` date field to each artist key and in the warm cache script if that date is > X days ago, fetch new info even though they're already in the db. Adding a flag to the script execution for forcing a full refresh of all artists and ignoring what's in the db would also be a good thing to do. 

I'm pretty tied up with the project I mentioned in the other issue currently but I can probably add this sometime in the next month to start cycling new artist info in

**Comment by leccelecce** [comment]
That solutions sounds straightforward - I'll have a crack at it and send a PR. 

In terms of > X days, can start off with X = 90? Feels like a reasonable compromise between processing time and staying up to date but can change as you see fit.

**Comment by leccelecce** [comment]
PR sent to enable the app to refresh data if > 90 days old. Note that this is implemented in redis-helper so it will apply equally to front-end requests or the warm cache script, so there is immediate impact to deploying it.

If you think it's needed I can look at working up some scripts to refresh in the background over a number of days, to have a "one click" solution to refreshing. Alternatively I could change it so that the front-end never calls the refresh code, only the warm cache script, so there isn't any risk of slowing down user requests.

**Comment by dot4qu** [comment]
Left a slew of comments. re: your last point, I think that's the quickest solution for now. I agree a periodic background refresh would be good, but I'd still prefer to keep any chance of a user getting stuck waiting for data to refresh at zero. There's zero spinner/waiting state so it just looks like the site is fully hanging
